### ISSUE TITLE
cfa wrapper no longer includes meanstructure

### ISSUE THREAD

**Issue by boboa4231** [JeroenDMulder/RI-CLPM#3]
The example of Ext3 of the RI-CLPM shows how to generate the measurement invariance models. But with the recent lavaan update, the cfa/sem wrappers do not automatically generate the meanstructures of the configural and weak invariance models - this is rectified by included 'meanstructure = True'. Otherwise the models will not be nested in the strong invariance model and the chi-sq different tests will not run.

**Comment by JeroenDMulder** [comment]
Hi @boboa4231, thank you for this update. I will I update the multiple indicator RI-CLPM syntax (and double-check if there are other things that are impacted by the recent lavaan update). Unfortunately, I will only do this in the first week of November, as my priorities right now are with finishing my PhD dissertation (it has to be handed in October 31st).

**Comment by JeroenDMulder** [comment]
Hi @boboa4231, I've finally had some time to look into this. However, I cannot seem to replicate the problem you describe using the latest version of lavaan. For all Extension 3 models I obtain estimates of the mean structure using the `cfa()` function, and without the `meanstructure = TRUE` argument. Could you provide some more information about how you found the issue?

**Comment by JeroenDMulder** [comment]
Can't reproduce the issue with information provided.
