### ISSUE TITLE
Please!!!Questions about multigroup RI-CLPM

### ISSUE THREAD

**Issue by MayZzzzzzz** [JeroenDMulder/RI-CLPM#7]
Recently, I tried to build a multi group RI-CLPM with three waves of data, but the model was unable to converge and exceeded the number of iterations. I tried to modify the convergence conditions and the number of iterations, but the model still cannot run. To reduce the number of parameters that need to be estimated, I set only one path is allowed to be unequal but multi group RI-CLPM still cannot run. Besides, If I run the RI-CLPM using overall data or run the RI-CLPM separately for male and female groups, the model works. At present, I have searched three articles on multi group RI-CLPM which all have four or five waves of data. Is it possible to use three-wave data to make multi group RI-CLPM? I just try to build multi group RI-CLPM with two variables, and I plan to do multi group RI-CLPM with three variables. If multi group RI-CLPM for two variables cannot be completed, can it also be implemented for three variables?

**Comment by JeroenDMulder** [comment]
It seems I have completely missed this issue, my apologies. Please open a new issue if the problem is still relevant.
