### ISSUE TITLE
ask for some help about RI-CLPM code

### ISSUE THREAD

**Issue by shsfdx383** [JeroenDMulder/RI-CLPM#8]

**Comment by shsfdx383** [comment]
hi~，I would like to know how to compare whether there are differences between different groups on a certain path with R. I'm not an expert on RI-CLPM, so I was wondering if you could help with the code

#________RICLPM
RICLPM <- '
  # Create between components (random intercepts)
  RIx =~ 1*x1 + 1*x2 + 1*x3
  RIm =~ 1*m1 + 1*m2 + 1*m3
  RIy =~ 1*y1 + 1*y2 + 1*y3

  # Create within-person centered variables
  wx1 =~ 1*x1
  wx2 =~ 1*x2
  wx3 =~ 1*x3 
  
  wm1 =~ 1*m1
  wm2 =~ 1*m2
  wm3 =~ 1*m3 
  
  wy1 =~ 1*y1
  wy2 =~ 1*y2
  wy3 =~ 1*y3

  # Estimate the lagged effects between the within-person centered variables.
  wx2 ~ wx1 + wm1 + wy1
  wm2 ~ wx1 + wm1 + wy1
  wy2 ~ wx1 + wm1 + wy1
  
  wx3 ~ wx2 + wm2 + wy2
  wm3 ~ wx2 + wm2 + wy2
  wy3 ~ wx2 + wm2 + wy2
  wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ age_1
  #wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ sex_2
  wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ pedu_1
  wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ medu_1
  wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ finc_1
  wx3 + wm3 + wy3 +  wx2 + wm2 + wy2 + wx1 + wm1 + wy1 ~ pm_1
  # Estimate the covariance between the within-person centered variables at the first wave. 
  wx1 ~~ wy1 # Covariance
  wx1 ~~ wm1
  wm1 ~~ wy1
  # Estimate the covariances between the residuals of the within-person centered variables (the innovations).
  wx2 ~~ wy2
  wx2 ~~ wm2
  wm2 ~~ wy2
  
  wx3 ~~ wy3
  wx3 ~~ wm3
  wm3 ~~ wy3
  
  # Estimate the variance and covariance of the random intercepts. 
  RIx ~~ RIx
  RIm ~~ RIm
  RIy ~~ RIy
  
  RIx ~~ RIy
  RIx ~~ RIm
  RIm ~~ RIy
  
  # Estimate the (residual) variance of the within-person centered variables.
  wx1 ~~ wx1 # Variances
  wm1 ~~ wm1  
  wy1 ~~ wy1 
  wx2 ~~ wx2 # Residual variances
  wm2 ~~ wm2  
  wy2 ~~ wy2
  wx3 ~~ wx3
  wm3 ~~ wm3  
  wy3 ~~ wy3
'
RICLPM.fit <- lavaan(RICLPM, 
                     data = data, 
                     missing="fiml", 
                     group = "sex_2",
                     mimic = "mplus",
                     #se = "boot",
                     #bootstrap = 1000,
                     meanstructure = T, 
                     int.ov.free = T) 
summary(RICLPM.fit)
summary(RICLPM.fit, fit.measures = TRUE)
par(mar = c(5, 4, 4, 6))
graph_sem(RICLPM.fit,curve=TRUE,layout = get_layout("wx1", "wx2", "wx3",
                                                    "wm1", "wm2", "wm3",
                                                    "wy1","wy2","wy3",
                                                    rows = 3))

**Comment by JeroenDMulder** [comment]
Hi @shsfdx383, 
Group differences in lagged regression coefficients can be thought of as moderation or interaction effects. This can be investigated by comparing a multiple group version of the RI-CLPM in which there are no constraints across the groups, with a model in which the lagged regression coefficients are constrained to be identical across the groups. See Extension 2 of [Mulder and Hamaker (2021](https://doi.org/10.1080/10705511.2020.1784738) for more information on how you can use the Chi-square difference test to compare these models.
